## Course Reccomendation System 

In [195]:
from __future__ import annotations # To prevent Subscript for class "list" will generate runtime exception; enclose type annotation in quotes
import seaborn as sns
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import random
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import random
import math
import scipy
from sklearn.preprocessing import MinMaxScaler
from Kmeans import * 
%matplotlib inline

In [196]:
random_state = 42

#### Applying Pre-processing steps on data: 


In [197]:
df=pd.read_excel('Course Recommendation System.xlsx')
df=df.drop(['ID','Start time','Completion time','Email','Name','Name(not mandatory)\n' ], axis=1).fillna(0.5)
df 

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  Machine Learning\n  \
0                      0.85       0.90           0.70                0.70   
1                      0.20       0.80           0.80                0.50   
2                      1.00       1.00           1.00                1.00   
3                      0.20       0.75           0.75                0.75   
4                      0.20       0.00           0.80                0.50   
..                      ...        ...            ...                 ...   
157                    0.50       0.70           0.60                0.50   
158                    0.00       0.70           0.70                0.00   
159                    0.40       0.90           0.80                0.70   
160                    0.20       0.40           0.70                0.70   
161                    0.90       0.40           0.40                0.70   

     Mathematics For Machine Learning\n  Visual Recognition\n  \
0                                  0.80                  0.50   
1                                  0.10                  0.20   
2                                  1.00                  0.80   
3                                  0.75                  0.75   
4                                  0.60                  0.40   
..                                  ...                   ...   
157                                0.30                  0.70   
158                                0.00                  0.00   
159                                0.40                  0.50   
160                                0.80                  0.50   
161                                0.90                  0.50   

     Natural Language Processing\n  Reinforcement Learning  ...  \
0                              0.5                     0.5  ...   
1                              0.5                     0.5  ...   
2                              0.9                     1.0  ...   
3                              0.5                     0.5  ...   
4                              0.4                     0.2  ...   
..                             ...                     ...  ...   
157                            0.5                     0.5  ...   
158                            0.5                     0.5  ...   
159                            0.4                     0.2  ...   
160                            0.5                     0.7  ...   
161                            0.5                     0.8  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          0.5                       0.5           0.5   
1                          0.5                       0.5           0.5   
2                          0.5                       0.5           0.5   
3                          0.5                       0.5           0.5   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
157                        0.5                       0.5           0.5   
158                        0.5                       0.5           0.5   
159                        0.5                       0.5   

In [198]:
df.columns

Index(['Data Structures and Algorithms', 'Computer Architecture\n',
       'Discrete Mathematics\n', 'Economics', 'Programming-2',
       'Machine Learning\n', 'Mathematics For Machine Learning\n',
       'Visual Recognition\n', 'Natural Language Processing\n',
       'Reinforcement Learning', 'Software Production Engineering\n',
       'Computer Graphics\n', 'Data Visualization\n',
       'Programming Languages\n', 'Cloud Computing\n',
       'Digital CMOS VLSI Design ', 'System design with FPGA ', 'ASIC design ',
       'VLSI Architecture Design\n',
       'High level synthesis and optimization of Digital Circuits ',
       'Digital Sociology ', 'Privacy in the Digital Age',
       'Technology Ethics and AI ', 'Techno-economics of networks ',
       'The Web and the Mind '],
      dtype='object')

In [199]:
def cluster_to_matrix(X_train,y_train,num_cluster):
    k=Kmeans(K=num_cluster,iter=150,p=2,random_state=random_state)
    y_pred=k.predict(np.array(X_train),choice=0)
    k.centroids=np.array(k.centroids, dtype='int')
    X_train2 = pd.concat([X_train,y_train,pd.DataFrame(y_pred,columns=["label"],dtype='int')],axis="columns")
    df_cluster_rep = X_train2.groupby(['label'], as_index=False).mean()
    df_cluster_rep.drop(labels="label",axis="columns",inplace=True)
    matrix = df_cluster_rep.to_numpy()
    return matrix,k 

Performing the task on dataset 

In [200]:
X = df[[df.columns[0],df.columns[1],df.columns[2],df.columns[3],df.columns[4]]]
y = df.drop(labels=["Data Structures and Algorithms","Computer Architecture\n","Discrete Mathematics\n","Economics","Programming-2"],axis="columns")

In [201]:
X

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  
0                      0.85       0.90           0.70  
1                      0.20       0.80           0.80  
2                      1.00       1.00           1.00  
3                      0.20       0.75           0.75  
4                      0.20       0.00           0.80  
..                      ...        ...            ...  
157                    0.50       0.70           0.60  
158                    0.00       0.70           0.70  
159                    0.40       0.90           0.80  
160                    0.20       0.40           0.70  
161                    0.90       0.40           0.40  

[162 rows x 5 columns]

In [202]:
y

Machine Learning\n  Mathematics For Machine Learning\n  \
0                  0.70                                0.80   
1                  0.50                                0.10   
2                  1.00                                1.00   
3                  0.75                                0.75   
4                  0.50                                0.60   
..                  ...                                 ...   
157                0.50                                0.30   
158                0.00                                0.00   
159                0.70                                0.40   
160                0.70                                0.80   
161                0.70                                0.90   

     Visual Recognition\n  Natural Language Processing\n  \
0                    0.50                            0.5   
1                    0.20                            0.5   
2                    0.80                            0.9   
3                    0.75                            0.5   
4                    0.40                            0.4   
..                    ...                            ...   
157                  0.70                            0.5   
158                  0.00                            0.5   
159                  0.50                            0.4   
160                  0.50                            0.5   
161                  0.50                            0.5   

     Reinforcement Learning  Software Production Engineering\n  \
0                       0.5                                0.5   
1                       0.5                                0.5   
2                       1.0                                0.0   
3                       0.5                                0.3   
4                       0.2                                0.7   
..                      ...                                ...   
157                     0.5                                0.5   
158                     0.5                                0.5   
159                     0.2                                0.7   
160                     0.7                                0.4   
161                     0.8                                0.5   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
0                    0.5                   0.5                      0.5   
1                    0.8                   0.5                      0.5   
2                    0.6                   0.0                      0.0   
3                    0.2                   0.5                      0.6   
4                    0.2                   0.2                      0.5   
..                   ...                   ...                      ...   
157                  0.0                   0.5                      0.5   
158                  1.0                   1.0                      0.0   
159                  0.7                   0.7                      0.7   
160                  0.4                   0.5                      0.6   
161                  0.5                   0.5                      0.4   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
0                  0.5                        0.5                       0.5   
1                  0.5                        0.5                       0.5   
2                  0.0                        0.5                       0.5   
3                  0.5                        0.5                       0.5   
4                  0.3                        0.0                       0.0   
..                 ...                        ...                       ...   
157                0.5                        0.5                       0.5   
158                0.5                        0.5                       0.5   
159                0.8                        0.5                       0.5   
160                0.5                     

In [203]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.05, shuffle=True,random_state=random_state)

In [204]:
matrix,kmeans_model = cluster_to_matrix(X_train,y_train,4)

In [205]:
matrix

array([[0.78041201, 0.69484375, 0.62519303, 0.58660201, 0.85434184,
        0.75628988, 0.69769662, 0.58566535, 0.57935216, 0.60863364,
        0.584375  , 0.49334162, 0.61566536, 0.5671875 , 0.58849259,
        0.439375  , 0.408125  , 0.363125  , 0.41171875, 0.365625  ,
        0.40703125, 0.51674473, 0.45625   , 0.4578125 , 0.54296875],
       [0.78166667, 0.65733333, 0.56666667, 0.62833333, 0.824     ,
        0.76833333, 0.66833333, 0.58366667, 0.45333333, 0.53      ,
        0.57      , 0.50833333, 0.55333333, 0.51333333, 0.48666667,
        0.38333333, 0.41666667, 0.41666667, 0.41333333, 0.43666667,
        0.49333333, 0.475     , 0.52      , 0.5       , 0.58333333],
       [0.86086957, 0.64347826, 0.6673913 , 0.50217391, 0.8673913 ,
        0.73913043, 0.63913043, 0.58913043, 0.44347826, 0.49565217,
        0.72173913, 0.37391304, 0.49565217, 0.59130435, 0.64347826,
        0.29565217, 0.30869565, 0.28695652, 0.28695652, 0.3       ,
        0.39565217, 0.41130435, 0.47956522, 0.

In [206]:
matrix.shape

(4, 25)

In [207]:
from SVD import * 
u,s,sigma,V_trans = SVD(matrix)

[[8.23645186 8.01888509 7.70417284 8.21349685]
 [8.01888509 7.87726878 7.50318986 8.01796071]
 [7.70417284 7.50318986 7.36553403 7.70964286]
 [8.21349685 8.01796071 7.70964286 8.29070574]]
[3.15458529e+01 1.27517907e-01 6.53374859e-02 3.12521164e-02]


In [208]:
matrix_clean = u@sigma@V_trans
matrix_clean = matrix_clean.astype('float')
matrix_clean

array([[0.78041201, 0.69484375, 0.62519303, 0.58660201, 0.85434184,
        0.75628988, 0.69769662, 0.58566535, 0.57935216, 0.60863364,
        0.584375  , 0.49334162, 0.61566536, 0.5671875 , 0.58849259,
        0.439375  , 0.408125  , 0.363125  , 0.41171875, 0.365625  ,
        0.40703125, 0.51674473, 0.45625   , 0.4578125 , 0.54296875],
       [0.78166667, 0.65733333, 0.56666667, 0.62833333, 0.824     ,
        0.76833333, 0.66833333, 0.58366667, 0.45333333, 0.53      ,
        0.57      , 0.50833333, 0.55333333, 0.51333333, 0.48666667,
        0.38333333, 0.41666667, 0.41666667, 0.41333333, 0.43666667,
        0.49333333, 0.475     , 0.52      , 0.5       , 0.58333333],
       [0.86086957, 0.64347826, 0.6673913 , 0.50217391, 0.8673913 ,
        0.73913043, 0.63913043, 0.58913043, 0.44347826, 0.49565217,
        0.72173913, 0.37391304, 0.49565217, 0.59130435, 0.64347826,
        0.29565217, 0.30869565, 0.28695652, 0.28695652, 0.3       ,
        0.39565217, 0.41130435, 0.47956522, 0.

In [209]:
def predict(datapoint,kmeans,matrix_clean):
    ''' 
        @input: Takes in a datapoint, kmeans object, and information matrix 
        @output: Returns: rating sorted with index for column name mapping
    '''
    y_pred = kmeans.predictPoint(datapoint)
    inferred_full = matrix_clean[y_pred]
    inferred = inferred_full[5:]
    sorted_ratings = []
    for idx,element in enumerate(inferred):
        sorted_ratings.append([element,idx+5])
    sorted_ratings.sort()
    sorted_ratings.reverse()
    return sorted_ratings 

In [210]:
X_test

Data Structures and Algorithms  Computer Architecture\n  \
158                             1.0                      0.0   
109                             1.0                      1.0   
131                             0.9                      0.7   
55                              1.0                      1.0   
94                              0.8                      0.3   
29                              1.0                      0.0   
101                             1.0                      0.8   
51                              1.0                      1.0   
100                             1.0                      1.0   

     Discrete Mathematics\n  Economics  Programming-2  
158                     0.0       0.70            0.7  
109                     0.0       1.00            0.5  
131                     0.9       0.85            0.8  
55                      0.0       1.00            1.0  
94                      0.7       0.40            0.9  
29                      0.0       0.00            0.0  
101                     0.5       0.30            0.8  
51                      0.6       0.40            1.0  
100                     1.0       1.00            0.0

In [211]:
y_test

Machine Learning\n  Mathematics For Machine Learning\n  \
158                0.00                                 0.0   
109                0.75                                 0.8   
131                0.60                                 0.7   
55                 1.00                                 1.0   
94                 1.00                                 1.0   
29                 1.00                                 1.0   
101                1.00                                 1.0   
51                 1.00                                 1.0   
100                1.00                                 1.0   

     Visual Recognition\n  Natural Language Processing\n  \
158                   0.0                            0.5   
109                   0.5                            0.5   
131                   0.7                            0.5   
55                    1.0                            0.5   
94                    0.6                            0.8   
29                    0.0                            0.0   
101                   1.0                            0.5   
51                    1.0                            1.0   
100                   1.0                            0.0   

     Reinforcement Learning  Software Production Engineering\n  \
158                     0.5                                0.5   
109                     0.5                                1.0   
131                     0.6                                0.7   
55                      0.5                                1.0   
94                      1.0                                1.0   
29                      0.0                                1.0   
101                     0.5                                0.8   
51                      1.0                                0.5   
100                     0.0                                1.0   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
158                  1.0                   1.0                      0.0   
109                  0.5                   0.5                      0.5   
131                  0.7                   0.7                      0.8   
55                   0.0                   0.0                      0.0   
94                   0.2                   0.7                      0.5   
29                   0.0                   0.0                      0.0   
101                  0.3                   0.9                      0.8   
51                   0.7                   0.5                      1.0   
100                  0.0                   0.0                      0.0   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
158               0.50                        0.5                       0.5   
109               0.50                        0.5                       1.0   
131               0.75                        0.5                       0.5   
55                0.00                        0.0                       0.0   
94                0.60                        0.0                       0.0   
29                0.00                        0.0                       0.0   
101               0.90                        0.0                       0.0   
51                0.50                        0.5                       0.5   
100               0.00                        0.0                       0.0   

     ASIC design   VLSI Architecture Design\n  \
158           0.5                         0.5   
109           0.7                         0.5   
131           0.5                         0.5   
55            0.0                         0.0   
94            0.0                         0.0   
29            0.0                         0.0   
101           0.0                         0.0   
51            0.4                         0.2   
100           0.0                         0.0   

     High level synthesis and optimization of Digital Circuits   \
158         

Trying Prediction on a sample data point from test set 

In [212]:
X_test.to_numpy()[0][:5]

array([1. , 0. , 0. , 0.7, 0.7])

In [213]:
sorted_ratings = predict(X_test.to_numpy()[0][:5],kmeans_model,matrix_clean)

In [214]:
s="Top 5 PREDICTED recommended electives are:\n"
for i in range(5):
    s+=df.columns[sorted_ratings[i][1]]+"\n"
print(s)

Top 5 PREDICTED recommended electives are:
Machine Learning

Mathematics For Machine Learning

Data Visualization

Reinforcement Learning
Cloud Computing




Comparing sample with the actual top 5

In [215]:
sorted_ratings = []
inferred = y_test.to_numpy()[1]
for idx,element in enumerate(inferred):
    sorted_ratings.append([element,idx+5])
sorted_ratings.sort()
sorted_ratings.reverse()

s="Top 5 ACTUAL recommended electives are:\n"
for i in range(5):
    s+=df.columns[sorted_ratings[i][1]]+"\n"
print(s)

Top 5 ACTUAL recommended electives are:
System design with FPGA 
Software Production Engineering

Mathematics For Machine Learning

Machine Learning

ASIC design 



In [216]:
X_test.shape

(9, 5)

### Functions for whole test series application 

In [217]:
def predict_for_dataset(X_test,kmeans_instance,matrix_clean):
    ''' Runs out inference and return predicted ratings of subjects 
        @input: X_test,kmeans object, clean_matrix after SVD
    '''
    X_test = X_test.to_numpy()
    y_pred = []
    for i in range(X_test.shape[0]):
        datapoint =X_test[i][:5]
        y_pred.append(predict(datapoint,kmeans_instance,matrix_clean))
    return np.array(y_pred)

In [218]:
y_pred = predict_for_dataset(X_test,kmeans_model,matrix_clean) 

In [219]:
y_pred.shape

(9, 20, 2)

In [220]:
def accuracy(y_pred,y_test,n=5):
    ''' Finds out % common subject in top 5 rated subjects (predicted and actual) 
        @input: predicted values and test dataset values 
        @output: accuracy value 
    '''
    y_test = y_test.to_numpy()
    sorted_ratings_actual = []
    for i in range(y_test.shape[0]):
        inferred = y_test[i]
        t = []
        for idx,element in enumerate(inferred):
            t.append([element,idx+5])
        t.sort()
        t.reverse()
        sorted_ratings_actual.append(np.array(t))
    sorted_ratings_actual = np.array(sorted_ratings_actual)
    
    total = 0 
    correct = 0 

    
    for i in range(len(sorted_ratings_actual)):
        total+=5
        temp = sorted_ratings_actual[i][:n]
        # if i ==1:
        #     print(temp)
        for j in range(n):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):correct+=1

    perecent_correct_for_datapoint = []

    for i in range(len(sorted_ratings_actual)):
        per_correct = 0 
        temp = sorted_ratings_actual[i][:n]
        # if i ==1:
        #     print(temp)
        for j in range(n):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):per_correct+=1
        perecent_correct_for_datapoint.append(per_correct/n)
    print("Total Entries received: ", len(sorted_ratings_actual)*n," Total Correct: ",correct)
    return 100*(correct/total),perecent_correct_for_datapoint,sorted_ratings_actual
        

In [221]:
overall_val,per_point_val,y_sorted_actual = accuracy(y_pred,y_test)

Total Entries received:  45  Total Correct:  19


In [222]:
overall_val

42.22222222222222

In [223]:
per_point_val

[0.2, 0.4, 0.4, 0.4, 0.6, 0.4, 0.8, 0.2, 0.4]

In [224]:
def display_subject(sorted_ratings,names,num_recs=5):
    '''
        @input: sorted_ratings list 
        @output: Names of subject corresponding
    '''
    s=""
    for i in range(num_recs):
        s+=names[int(sorted_ratings[i][1])]+"\n"
    return s 

In [225]:
print(display_subject(y_pred[1],df.columns))

Machine Learning

Mathematics For Machine Learning

Data Visualization

Reinforcement Learning
Cloud Computing




In [226]:
print(display_subject(y_sorted_actual[1],df.columns))

System design with FPGA 
Software Production Engineering

Mathematics For Machine Learning

Machine Learning

ASIC design 



#### UI for easy testing and prediction 

In [227]:
!pip install gradio
import gradio as gr

^C
ERROR: Operation cancelled by user


In [ ]:
text = ["Data Structures and Algorithms","Computer Architecture","Discrete Mathematics","Economics","Programming-2",
       'Machine Learning', 'Mathematics For Machine Learning',
       'Visual Recognition', 'Natural Language Processing',
       'Reinforcement Learning', 'Software Production Engineering',
       'Computer Graphics', 'Data Visualization',
       'Programming Languages', 'Cloud Computing',
       'Digital CMOS VLSI Design ', 'System design with FPGA ', 'ASIC design ',
       'VLSI Architecture Design',
       'High level synthesis and optimization of Digital Circuits',
       'Digital Sociology ', 'Privacy in the Digital Age',
       'Technology Ethics and AI ', 'Techno-economics of networks ',
       'The Web and the Mind ']
def ui(name,num_recs,c1,c2,c3,c4,c5):
    print(name)
    core = np.array([c1,c2,c3,c4,c5])
    subjects=predict(core,kmeans_model,matrix_clean)
    return display_subject(subjects,text,num_recs)
    
    
    
demo = gr.Interface(fn=ui, inputs=[gr.Text(label="Enter your Name (Optional)"),
                                      gr.Slider(int(1),int(20),step=1,label="Number of subjects you want us to recommend?"),
                                      gr.Slider(0,1,label="Data Structures and Algorithms",info="Enter a value between 0 and 1"),
                                      gr.Slider(0,1,label="Computer Architecture",info="Enter a value between 0 and 1"),
                                      gr.Slider(0,1,label="Discrete Mathematics",info="Enter a value between 0 and 1"),
                                      gr.Slider(0,1,label="Economics",info="Enter a value between 0 and 1"),
                                      gr.Slider(0,1,label="Programming-2",info="Enter a value between 0 and 1")], 
                                    outputs=gr.Text(label="Here are your recommendations:(in decreasing order/ preference) "))

demo.launch(share=True) 

Running on local URL:  http://127.0.0.1:7860


KeyboardInterrupt: 