## Course Reccomendation System 

In [1]:
from __future__ import annotations # To prevent Subscript for class "list" will generate runtime exception; enclose type annotation in quotes
import seaborn as sns
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import random
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import random
import math
import scipy
from sklearn.preprocessing import MinMaxScaler
from Kmeans import * 
%matplotlib inline
from sklearn.cluster import KMeans

In [2]:
random_state = 42

#### Applying Pre-processing steps on data: 


In [3]:
df=pd.read_excel('Course Recommendation System.xlsx')
df=df.drop(['ID','Start time','Completion time','Email','Name','Name(not mandatory)\n' ], axis=1).fillna(0.5)
df 

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  Machine Learning\n  \
0                      0.85       0.90           0.70                0.70   
1                      0.20       0.80           0.80                0.50   
2                      1.00       1.00           1.00                1.00   
3                      0.20       0.75           0.75                0.75   
4                      0.20       0.00           0.80                0.50   
..                      ...        ...            ...                 ...   
157                    0.50       0.70           0.60                0.50   
158                    0.00       0.70           0.70                0.00   
159                    0.40       0.90           0.80                0.70   
160                    0.20       0.40           0.70                0.70   
161                    0.90       0.40           0.40                0.70   

     Mathematics For Machine Learning\n  Visual Recognition\n  \
0                                  0.80                  0.50   
1                                  0.10                  0.20   
2                                  1.00                  0.80   
3                                  0.75                  0.75   
4                                  0.60                  0.40   
..                                  ...                   ...   
157                                0.30                  0.70   
158                                0.00                  0.00   
159                                0.40                  0.50   
160                                0.80                  0.50   
161                                0.90                  0.50   

     Natural Language Processing\n  Reinforcement Learning  ...  \
0                              0.5                     0.5  ...   
1                              0.5                     0.5  ...   
2                              0.9                     1.0  ...   
3                              0.5                     0.5  ...   
4                              0.4                     0.2  ...   
..                             ...                     ...  ...   
157                            0.5                     0.5  ...   
158                            0.5                     0.5  ...   
159                            0.4                     0.2  ...   
160                            0.5                     0.7  ...   
161                            0.5                     0.8  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          0.5                       0.5           0.5   
1                          0.5                       0.5           0.5   
2                          0.5                       0.5           0.5   
3                          0.5                       0.5           0.5   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
157                        0.5                       0.5           0.5   
158                        0.5                       0.5           0.5   
159                        0.5                       0.5   

In [4]:
def cluster_to_matrix(X_train,y_train,num_cluster):
    # k=Kmeans(K=num_cluster,iter=150,p=2,random_state=random_state)
    # y_pred=k.predict(np.array(X_train),choice=0)
    k = KMeans(n_clusters = num_cluster, random_state=42)
    k.fit(X_train)
    y_pred = k.predict(np.array(X_train))
    k.centroids=np.array(k.cluster_centers_, dtype='int')
    X_train2 = pd.concat([X_train,y_train,pd.DataFrame(y_pred,columns=["label"],dtype='int')],axis="columns")
    df_cluster_rep = X_train2.groupby(['label'], as_index=False).mean()
    df_cluster_rep.drop(labels="label",axis="columns",inplace=True)
    matrix = df_cluster_rep.to_numpy()
    return matrix,k 

Performing the task on dataset 

In [5]:
X = df[[df.columns[0],df.columns[1],df.columns[2],df.columns[3],df.columns[4]]]
y = df.drop(labels=["Data Structures and Algorithms","Computer Architecture\n","Discrete Mathematics\n","Economics","Programming-2"],axis="columns")

In [6]:
X

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  
0                      0.85       0.90           0.70  
1                      0.20       0.80           0.80  
2                      1.00       1.00           1.00  
3                      0.20       0.75           0.75  
4                      0.20       0.00           0.80  
..                      ...        ...            ...  
157                    0.50       0.70           0.60  
158                    0.00       0.70           0.70  
159                    0.40       0.90           0.80  
160                    0.20       0.40           0.70  
161                    0.90       0.40           0.40  

[162 rows x 5 columns]

In [7]:
y

Machine Learning\n  Mathematics For Machine Learning\n  \
0                  0.70                                0.80   
1                  0.50                                0.10   
2                  1.00                                1.00   
3                  0.75                                0.75   
4                  0.50                                0.60   
..                  ...                                 ...   
157                0.50                                0.30   
158                0.00                                0.00   
159                0.70                                0.40   
160                0.70                                0.80   
161                0.70                                0.90   

     Visual Recognition\n  Natural Language Processing\n  \
0                    0.50                            0.5   
1                    0.20                            0.5   
2                    0.80                            0.9   
3                    0.75                            0.5   
4                    0.40                            0.4   
..                    ...                            ...   
157                  0.70                            0.5   
158                  0.00                            0.5   
159                  0.50                            0.4   
160                  0.50                            0.5   
161                  0.50                            0.5   

     Reinforcement Learning  Software Production Engineering\n  \
0                       0.5                                0.5   
1                       0.5                                0.5   
2                       1.0                                0.0   
3                       0.5                                0.3   
4                       0.2                                0.7   
..                      ...                                ...   
157                     0.5                                0.5   
158                     0.5                                0.5   
159                     0.2                                0.7   
160                     0.7                                0.4   
161                     0.8                                0.5   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
0                    0.5                   0.5                      0.5   
1                    0.8                   0.5                      0.5   
2                    0.6                   0.0                      0.0   
3                    0.2                   0.5                      0.6   
4                    0.2                   0.2                      0.5   
..                   ...                   ...                      ...   
157                  0.0                   0.5                      0.5   
158                  1.0                   1.0                      0.0   
159                  0.7                   0.7                      0.7   
160                  0.4                   0.5                      0.6   
161                  0.5                   0.5                      0.4   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
0                  0.5                        0.5                       0.5   
1                  0.5                        0.5                       0.5   
2                  0.0                        0.5                       0.5   
3                  0.5                        0.5                       0.5   
4                  0.3                        0.0                       0.0   
..                 ...                        ...                       ...   
157                0.5                        0.5                       0.5   
158                0.5                        0.5                       0.5   
159                0.8                        0.5                       0.5   
160                0.5                     

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.05, shuffle=True,random_state=random_state)

In [9]:
num_cluster = 5

In [10]:
matrix,kmeans_model = cluster_to_matrix(X_train,y_train,num_cluster)

/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [11]:
matrix

array([[0.76840567, 0.67184615, 0.61557467, 0.55142351, 0.86119812,
        0.74003927, 0.67927052, 0.56742435, 0.56428521, 0.60080851,
        0.59384615, 0.47652097, 0.59850127, 0.58923077, 0.58251578,
        0.43261538, 0.40184615, 0.35753846, 0.40538462, 0.36      ,
        0.41615385, 0.49341019, 0.45846154, 0.46153846, 0.52692308],
       [0.86451613, 0.79419355, 0.72419355, 0.66451613, 0.87806452,
        0.81129032, 0.73709677, 0.65032258, 0.59322581, 0.6383871 ,
        0.53387097, 0.50806452, 0.56612903, 0.48064516, 0.49677419,
        0.39354839, 0.41935484, 0.41612903, 0.42580645, 0.43225806,
        0.45      , 0.41483871, 0.46548387, 0.44677419, 0.52258065],
       [0.81538462, 0.71153846, 0.48461538, 0.65384615, 0.87692308,
        0.75      , 0.70769231, 0.46923077, 0.58461538, 0.52307692,
        0.5       , 0.42384615, 0.40769231, 0.36153846, 0.44615385,
        0.42307692, 0.46153846, 0.46153846, 0.43846154, 0.34615385,
        0.46153846, 0.46923077, 0.43846154, 0.

In [12]:
matrix.shape

(5, 25)

In [13]:
from SVD import * 
u,s,sigma,V_trans = ReducedSVD(matrix,to_remove=0)

[[7.98925634 8.32793366 7.61913972 7.85361258 7.73200039]
 [8.32793366 8.77652352 8.01341687 8.16654032 8.07810573]
 [7.61913972 8.01341687 7.43973432 7.49926496 7.35349145]
 [7.85361258 8.16654032 7.49926496 7.89853395 7.65212963]
 [7.73200039 8.07810573 7.35349145 7.65212963 7.6439892 ]]
[3.93032974e+01 2.25644517e-01 1.34912279e-01 5.42414986e-02
 2.99416318e-02]
[6.2692342  0.47502054 0.36730407 0.23289804 0.1730365 ]


In [14]:
matrix_clean = u@sigma@V_trans
matrix_clean = matrix_clean.astype('float')
matrix_clean

array([[0.76840567, 0.67184615, 0.61557467, 0.55142351, 0.86119812,
        0.74003927, 0.67927052, 0.56742435, 0.56428521, 0.60080851,
        0.59384615, 0.47652097, 0.59850127, 0.58923077, 0.58251578,
        0.43261538, 0.40184615, 0.35753846, 0.40538462, 0.36      ,
        0.41615385, 0.49341019, 0.45846154, 0.46153846, 0.52692308],
       [0.86451613, 0.79419355, 0.72419355, 0.66451613, 0.87806452,
        0.81129032, 0.73709677, 0.65032258, 0.59322581, 0.6383871 ,
        0.53387097, 0.50806452, 0.56612903, 0.48064516, 0.49677419,
        0.39354839, 0.41935484, 0.41612903, 0.42580645, 0.43225806,
        0.45      , 0.41483871, 0.46548387, 0.44677419, 0.52258065],
       [0.81538462, 0.71153846, 0.48461538, 0.65384615, 0.87692308,
        0.75      , 0.70769231, 0.46923077, 0.58461538, 0.52307692,
        0.5       , 0.42384615, 0.40769231, 0.36153846, 0.44615385,
        0.42307692, 0.46153846, 0.46153846, 0.43846154, 0.34615385,
        0.46153846, 0.46923077, 0.43846154, 0.

In [15]:
t = X_test.to_numpy()[0][:5]
t.shape


(5,)

In [16]:
t.reshape(5, 1)

array([[1. ],
       [0. ],
       [0. ],
       [0.7],
       [0.7]])

In [17]:
t.shape

(5,)

In [18]:
def predict(datapoint,kmeans,matrix_clean):
    ''' 
        @input: Takes in a datapoint, kmeans object, and information matrix 
        @output: Returns: rating sorted with index for column name mapping
    '''
    # y_pred = kmeans.predictPoint(datapoint) 
    y_pred = kmeans.predict(datapoint.reshape(1, 5))
    inferred_full = matrix_clean[y_pred]
    inferred = inferred_full[0][5:]
    sorted_ratings = []
    for idx,element in enumerate(inferred):
        sorted_ratings.append([element,idx+5])
    sorted_ratings.sort()
    sorted_ratings.reverse()
    return sorted_ratings 

In [19]:
X_test

Data Structures and Algorithms  Computer Architecture\n  \
158                             1.0                      0.0   
109                             1.0                      1.0   
131                             0.9                      0.7   
55                              1.0                      1.0   
94                              0.8                      0.3   
29                              1.0                      0.0   
101                             1.0                      0.8   
51                              1.0                      1.0   
100                             1.0                      1.0   

     Discrete Mathematics\n  Economics  Programming-2  
158                     0.0       0.70            0.7  
109                     0.0       1.00            0.5  
131                     0.9       0.85            0.8  
55                      0.0       1.00            1.0  
94                      0.7       0.40            0.9  
29                      0.0       0.00            0.0  
101                     0.5       0.30            0.8  
51                      0.6       0.40            1.0  
100                     1.0       1.00            0.0

In [20]:
y_test

Machine Learning\n  Mathematics For Machine Learning\n  \
158                0.00                                 0.0   
109                0.75                                 0.8   
131                0.60                                 0.7   
55                 1.00                                 1.0   
94                 1.00                                 1.0   
29                 1.00                                 1.0   
101                1.00                                 1.0   
51                 1.00                                 1.0   
100                1.00                                 1.0   

     Visual Recognition\n  Natural Language Processing\n  \
158                   0.0                            0.5   
109                   0.5                            0.5   
131                   0.7                            0.5   
55                    1.0                            0.5   
94                    0.6                            0.8   
29                    0.0                            0.0   
101                   1.0                            0.5   
51                    1.0                            1.0   
100                   1.0                            0.0   

     Reinforcement Learning  Software Production Engineering\n  \
158                     0.5                                0.5   
109                     0.5                                1.0   
131                     0.6                                0.7   
55                      0.5                                1.0   
94                      1.0                                1.0   
29                      0.0                                1.0   
101                     0.5                                0.8   
51                      1.0                                0.5   
100                     0.0                                1.0   

     Computer Graphics\n  Data Visualization\n  Programming Languages\n  \
158                  1.0                   1.0                      0.0   
109                  0.5                   0.5                      0.5   
131                  0.7                   0.7                      0.8   
55                   0.0                   0.0                      0.0   
94                   0.2                   0.7                      0.5   
29                   0.0                   0.0                      0.0   
101                  0.3                   0.9                      0.8   
51                   0.7                   0.5                      1.0   
100                  0.0                   0.0                      0.0   

     Cloud Computing\n  Digital CMOS VLSI Design   System design with FPGA   \
158               0.50                        0.5                       0.5   
109               0.50                        0.5                       1.0   
131               0.75                        0.5                       0.5   
55                0.00                        0.0                       0.0   
94                0.60                        0.0                       0.0   
29                0.00                        0.0                       0.0   
101               0.90                        0.0                       0.0   
51                0.50                        0.5                       0.5   
100               0.00                        0.0                       0.0   

     ASIC design   VLSI Architecture Design\n  \
158           0.5                         0.5   
109           0.7                         0.5   
131           0.5                         0.5   
55            0.0                         0.0   
94            0.0                         0.0   
29            0.0                         0.0   
101           0.0                         0.0   
51            0.4                         0.2   
100           0.0                         0.0   

     High level synthesis and optimization of Digital Circuits   \
158         

Trying Prediction on a sample data point from test set 

In [21]:
X_test.to_numpy()[0][:5]

array([1. , 0. , 0. , 0.7, 0.7])

In [22]:
sorted_ratings = predict(X_test.to_numpy()[0][:5],kmeans_model,matrix_clean)

/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [23]:
s="Top 5 PREDICTED recommended electives are:\n"
for i in range(5):
    s+=df.columns[sorted_ratings[i][1]]+"\n"
print(s)

Top 5 PREDICTED recommended electives are:
Machine Learning

Software Production Engineering

Mathematics For Machine Learning

The Web and the Mind 
Visual Recognition




Comparing sample with the actual top 5

In [24]:
inferred = y_test.to_numpy()[0]
for idx,element in enumerate(inferred):
    sorted_ratings.append([element,idx+5])
sorted_ratings.sort()
sorted_ratings.reverse()
s="Top 5 ACTUAL recommended electives are:\n"
for i in range(5):
    s+=df.columns[sorted_ratings[i][1]]+"\n"
print(s)

Top 5 ACTUAL recommended electives are:
Data Visualization

Computer Graphics

Machine Learning

Software Production Engineering

Mathematics For Machine Learning




In [25]:
X_test.shape

(9, 5)

### Functions for whole test series application 

In [26]:
def predict_for_dataset(X_test,kmeans_instance,matrix_clean):
    ''' Runs out inference and return predicted ratings of subjects 
        @input: X_test,kmeans object, clean_matrix after SVD
    '''
    X_test = X_test.to_numpy()
    y_pred = []
    for i in range(X_test.shape[0]):
        datapoint =X_test[i][:5]
        y_pred.append(predict(datapoint,kmeans_instance,matrix_clean))
    return np.array(y_pred)

In [27]:
y_pred = predict_for_dataset(X_test,kmeans_model,matrix_clean) 

/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
/Users/monjoy/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450

In [28]:
y_pred.shape

(9, 20, 2)

In [29]:
def accuracy(y_pred,y_test):
    ''' Finds out % common subject in top 5 rated subjects (predicted and actual) 
        @input: predicted values and test dataset values 
        @output: accuracy value 
    '''
    y_test = y_test.to_numpy()
    sorted_ratings_actual = []
    for i in range(y_test.shape[0]):
        inferred = y_test[i]
        t = []
        for idx,element in enumerate(inferred):
            t.append([element,idx+5])
        t.sort()
        t.reverse()
        sorted_ratings_actual.append(np.array(t))
    sorted_ratings_actual = np.array(sorted_ratings_actual)
    
    total = 0 
    correct = 0 

    
    for i in range(len(sorted_ratings_actual)):
        total+=5
        temp = sorted_ratings_actual[i][:5]
        # if i ==1:
        #     print(temp)
        for j in range(5):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):correct+=1

    perecent_correct_for_datapoint = []

    for i in range(len(sorted_ratings_actual)):
        per_correct = 0 
        temp = sorted_ratings_actual[i][:5]
        # if i ==1:
        #     print(temp)
        for j in range(5):
            for k in range(len(temp)):
                if(y_pred[i][j][1]==temp[k][1]):per_correct+=1
        perecent_correct_for_datapoint.append(per_correct/5)
    print("Total Entries received: ", len(sorted_ratings_actual)*5," Total Correct: ",correct)
    return 100*(correct/total),perecent_correct_for_datapoint,sorted_ratings_actual
        

In [30]:
overall_val,per_point_val,y_sorted_actual = accuracy(y_pred,y_test)

Total Entries received:  45  Total Correct:  20


In [31]:
overall_val

44.44444444444444

In [32]:
per_point_val

[0.0, 0.4, 0.2, 0.6, 0.8, 0.6, 0.8, 0.0, 0.6]

In [33]:
def display_subject(sorted_ratings,names):
    '''
        @input: sorted_ratings list 
        @output: Names of subject corresponding
    '''
    s=""
    for i in range(5):
        s+=names[int(sorted_ratings[i][1])]+"\n"
    return s 

In [34]:
print(display_subject(y_pred[1],df.columns))

Machine Learning

Mathematics For Machine Learning

Visual Recognition

Reinforcement Learning
Natural Language Processing




In [35]:
print(display_subject(y_sorted_actual[1],df.columns))

System design with FPGA 
Software Production Engineering

Mathematics For Machine Learning

Machine Learning

ASIC design 

