In [742]:
import pandas as pd
import numpy as np
import math
from decimal import Decimal

In [743]:
df = pd.read_excel('Course Recommendation System.xlsx')

In [744]:
df

ID          Start time     Completion time      Email  Name  \
0      6 2023-01-30 14:04:19 2023-01-30 14:05:54  anonymous   NaN   
1      7 2023-01-30 14:04:44 2023-01-30 14:12:35  anonymous   NaN   
2      8 2023-01-30 14:11:07 2023-01-30 14:12:47  anonymous   NaN   
3      9 2023-01-30 19:10:54 2023-01-30 19:12:35  anonymous   NaN   
4     10 2023-01-30 22:58:02 2023-01-30 23:00:34  anonymous   NaN   
..   ...                 ...                 ...        ...   ...   
157  163 2023-02-25 09:36:58 2023-02-25 09:39:26  anonymous   NaN   
158  164 2023-02-25 10:32:07 2023-02-25 10:33:29  anonymous   NaN   
159  165 2023-02-25 16:23:18 2023-02-25 16:25:04  anonymous   NaN   
160  166 2023-02-27 09:46:02 2023-02-27 09:46:57  anonymous   NaN   
161  167 2023-02-27 09:47:04 2023-02-27 09:47:42  anonymous   NaN   

      Name(not mandatory)\n  Data Structures and Algorithms  \
0                       NaN                            0.30   
1                Rahul Jain                            0.70   
2                       NaN                            0.70   
3              Adrij Sharma                            0.65   
4                       NaN                            0.70   
..                      ...                             ...   
157  Shivankar Pilligundla                             0.00   
158                     NaN                            1.00   
159                     NaN                            0.60   
160                     NaN                            0.80   
161                       R                            0.40   

     Computer Architecture\n  Discrete Mathematics\n  Economics  ...  \
0                       0.85                    0.85       0.90  ...   
1                       0.80                    0.20       0.80  ...   
2                       0.00                    1.00       1.00  ...   
3                       0.70                    0.20       0.75  ...   
4                       0.60                    0.20       0.00  ...   
..                       ...                     ...        ...  ...   
157                     1.00                    0.50       0.70  ...   
158                     0.00                    0.00       0.70  ...   
159                     0.30                    0.40       0.90  ...   
160                     0.60                    0.20       0.40  ...   
161                     0.70                    0.90       0.40  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          NaN                       NaN           NaN   
1                          NaN                       NaN           NaN   
2                          NaN                       NaN           NaN   
3                          NaN                       NaN           NaN   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
157                        NaN                       NaN           NaN   
158                        NaN                       NaN           NaN   
159                        NaN                       NaN           NaN   
160                        NaN                       NaN           NaN   
161                        NaN                       NaN           NaN   

     VLSI Architecture Design\n  \
0                           NaN   
1                           NaN   
2                           NaN   
3                           NaN   
4                           0.0   
..                          ...   
157                         NaN   
158                         NaN   
159                         NaN   
160                         NaN   
161                         NaN   

     High level synthesis and optimization of Digital Circuits   \
0                                                  NaN            
1                                                  NaN            
2                                           

In [745]:
df.drop(labels = ['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Name(not mandatory)\n'], axis = 1, inplace = True)

In [746]:
df.fillna(0.5, inplace=True)

In [747]:
df

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
157                            0.00                     1.00   
158                            1.00                     0.00   
159                            0.60                     0.30   
160                            0.80                     0.60   
161                            0.40                     0.70   

     Discrete Mathematics\n  Economics  Programming-2  Machine Learning\n  \
0                      0.85       0.90           0.70                0.70   
1                      0.20       0.80           0.80                0.50   
2                      1.00       1.00           1.00                1.00   
3                      0.20       0.75           0.75                0.75   
4                      0.20       0.00           0.80                0.50   
..                      ...        ...            ...                 ...   
157                    0.50       0.70           0.60                0.50   
158                    0.00       0.70           0.70                0.00   
159                    0.40       0.90           0.80                0.70   
160                    0.20       0.40           0.70                0.70   
161                    0.90       0.40           0.40                0.70   

     Mathematics For Machine Learning\n  Visual Recognition\n  \
0                                  0.80                  0.50   
1                                  0.10                  0.20   
2                                  1.00                  0.80   
3                                  0.75                  0.75   
4                                  0.60                  0.40   
..                                  ...                   ...   
157                                0.30                  0.70   
158                                0.00                  0.00   
159                                0.40                  0.50   
160                                0.80                  0.50   
161                                0.90                  0.50   

     Natural Language Processing\n  Reinforcement Learning  ...  \
0                              0.5                     0.5  ...   
1                              0.5                     0.5  ...   
2                              0.9                     1.0  ...   
3                              0.5                     0.5  ...   
4                              0.4                     0.2  ...   
..                             ...                     ...  ...   
157                            0.5                     0.5  ...   
158                            0.5                     0.5  ...   
159                            0.4                     0.2  ...   
160                            0.5                     0.7  ...   
161                            0.5                     0.8  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          0.5                       0.5           0.5   
1                          0.5                       0.5           0.5   
2                          0.5                       0.5           0.5   
3                          0.5                       0.5           0.5   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
157                        0.5                       0.5           0.5   
158                        0.5                       0.5           0.5   
159                        0.5                       0.5   

In [748]:
A = np.asarray(df)

In [749]:
A

array([[0.3 , 0.85, 0.85, ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.8 , 0.2 , ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.  , 1.  , ..., 0.5 , 0.5 , 0.5 ],
       ...,
       [0.6 , 0.3 , 0.4 , ..., 0.5 , 0.5 , 1.  ],
       [0.8 , 0.6 , 0.2 , ..., 0.5 , 0.5 , 0.5 ],
       [0.4 , 0.7 , 0.9 , ..., 0.5 , 0.5 , 0.5 ]])

# Truncated SVD -
We will do the folloing steps:-
* QR-Deccomposition
* Eigen Decomposition
* Truncated Singular Value Decomposition

In [750]:
def vector_norm(x):
    """Compute the L2 norm of a vector."""
    return Decimal(np.dot(x, x)).sqrt()

def qr_decomposition(A):
    """
    Compute the QR decomposition of a matrix A using the Gram-Schmidt algorithm.

    Parameters:
    A (numpy.ndarray): The matrix to decompose.

    Returns:
    (numpy.ndarray, numpy.ndarray): A tuple of Q and R matrices that represent the QR decomposition of A, where:
        Q (numpy.ndarray): The orthogonal matrix Q.
        R (numpy.ndarray): The upper triangular matrix R.
    """
    # Get the shape of the input matrix
    m, n = A.shape

    # Initialize the matrices
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    # Perform the Gram-Schmidt orthogonalization
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        # R[j, j] = np.linalg.norm(v)
        R[j, j] = vector_norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

In [751]:
def eig(A):
    """
    Compute the eigenvalues and eigenvectors of a matrix A using the power iteration method.

    Parameters:
    A (numpy.ndarray): The matrix to compute eigenvalues and eigenvectors.

    Returns:
    (eigvals, eigvecs): A tuple of arrays that represent the eigenvalues and eigenvectors of A, where:
        eigvals (numpy.ndarray): The eigenvalues of A.
        eigvecs (numpy.ndarray): The eigenvectors of A.
    """
    # set the number of iterations and tolerance level
    max_iter = 100
    tol = 1e-6

    # initialize the eigenvectors
    m, n = A.shape
    eigvecs = np.random.randn(n, n)

    # compute the largest eigenvalue and eigenvector
    for i in range(max_iter):
        # compute the new eigenvector
        eigvecs_new = A @ eigvecs
        # eigvecs_new, _ = np.linalg.qr(eigvecs_new)
        eigvecs_new, _ = qr_decomposition(eigvecs_new)
        if np.allclose(eigvecs_new, eigvecs, rtol=tol):
            break
        eigvecs = eigvecs_new

    # compute the eigenvalues
    eigvals = np.diag(eigvecs.T @ A @ eigvecs)

    return eigvals, eigvecs


In [752]:
def SVD(A):
    """
    Compute Singular Value Decomposition of matrix A using NumPy.

    Args:
        A: numpy.array, matrix to be decomposed

    Returns:
        U: numpy.array, matrix containing left singular vectors
        s: numpy.array, array containing singular values
        V_T: numpy.array, matrix containing right singular vectors (transposed)
    """
    # Compute the eigenvectors and eigenvalues of A*At or At*A, whichever is smaller
    if A.shape[0] < A.shape[1]:
        S = np.dot(A.T, A)
    else:
        S = np.dot(A, A.T)
        
    eigvals, eigvecs = np.linalg.eig(S) #NOT ALLOWED
    # eigvals, eigvecs = eig(S)

    # Sort the eigenvectors by descending eigenvalues
    sorted_indices = np.argsort(eigvals)[::-1]
    eigvals = eigvals[sorted_indices]
    eigvecs = eigvecs[:,sorted_indices]

    # Compute the singular values and their reciprocals
    s = np.sqrt(eigvals)
    s = s[s > 10e-6]
    s_inv = np.zeros_like(A.T)
    np.fill_diagonal(s_inv, 1.0 / s)

    # Compute the left and right singular vectors
    # if(A.shape[0] > A.shape[1]):
    if(A.shape[0] < A.shape[1]):
        U = np.dot(A, np.dot(eigvecs, s_inv))
        V_T = eigvecs.T
        if(len(s) != V_T.shape[0]): V_T = V_T[:len(s) - V_T.shape[0], :] 

    else:
        U = eigvecs
        V_T = np.dot(s_inv, np.dot(U.T, A))
        if(len(s) != U.shape[1]): U = U[:, :len(s) - U.shape[1]]


    
    # else: 
    #     V_T = np.dot(s_inv, np.dot(eigvecs, A))
    #     U = eigvecs.T
    #     if(len(s) != V_T.shape[0]): V_T = V_T[:len(s) - V_T.shape[0], :]
        

    sigma = np.zeros([U.shape[1], V_T.shape[0]])
    # sigma = np.zeros([len(s), len(s)])
    # sigma = np.diag(s)
    # if(A.shape[0] < A.shape[1]):
    for i in range(len(s)):
        sigma[i, i] = s[i]
    # else:
    #     for i in range(len(s)):
    #         sigma[i, i] = s[i]

    return U, s, sigma, V_T

# SVD on Data

In [753]:
tryy = np.array([[0.6, 0.4, 0.9], [0.3, 0.1, 0.7], [0.1, 0.5, 0.8], [0.55, 0.45, 0.5], [0.7, 0.7 , 0.7]])
# tryy = np.array([[0.6, 0.4, 0.9], [0.3, 0.1, 0.7]])

In [754]:
U, s, sigma, V_trans = SVD(tryy)

In [755]:
U @ sigma @V_trans

array([[0.6 , 0.4 , 0.9 ],
       [0.3 , 0.1 , 0.7 ],
       [0.1 , 0.5 , 0.8 ],
       [0.55, 0.45, 0.5 ],
       [0.7 , 0.7 , 0.7 ]])

In [756]:
sigma.shape

(3, 3)

In [757]:
np.allclose(U @ sigma @ V_trans, tryy)

True

# Reduced SVD

In [758]:
def ReducedSVD(A, threshold = 0, to_remove = 0):
    U, s, sigma, V_trans = SVD(A)

    # While converting to python code we will convert into GUI asking-
    #       - Removal based on:-
    #       - 1. Hyper parameter
    #       - 2. Threshold
    
    # Removal based on hyper parameter
    if(to_remove < len(s) and to_remove > 0):
        s = s[:-to_remove]
        print(s)
        U = U[:, :-to_remove]
        V_trans = V_trans[:-to_remove, :]
        sigma = sigma[:-to_remove, :-to_remove]

    elif(to_remove < 0):
        print("The number of eigen values to be romved is Invalid!!")
        exit()
        
    # Removal based on threshold
    if(threshold < s[0] and threshold > 0):
        s = s[s >= threshold]
        print(s)
        U = U[:, :len(s)]
        V_trans = V_trans[:len(s), :]
        sigma = sigma[:len(s), :len(s)]

    elif(threshold < 0):
        print("Invalid threshold value!!")
        exit()
        
    return U, s, sigma, V_trans
    

# Reduced SVD on Data

In [759]:
u1, s2, sig1, vt1 = ReducedSVD(A,0,0)

/home/karanjitsaha/.local/lib/python3.8/site-packages/numpy/lib/index_tricks.py:910: ComplexWarning: Casting complex values to real discards the imaginary part
  a.flat[:end:step] = val
/tmp/ipykernel_939/2346851272.py:58: ComplexWarning: Casting complex values to real discards the imaginary part
  sigma[i, i] = s[i]


In [760]:
u1 @ sig1 @ vt1

array([[ 3.00000000e-01+0.j,  8.50000000e-01+0.j,  8.50000000e-01+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         5.00000000e-01+0.j],
       [ 7.00000000e-01+0.j,  8.00000000e-01+0.j,  2.00000000e-01+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         5.00000000e-01+0.j],
       [ 7.00000000e-01+0.j, -2.41614312e-15+0.j,  1.00000000e+00+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         5.00000000e-01+0.j],
       ...,
       [ 6.00000000e-01+0.j,  3.00000000e-01+0.j,  4.00000000e-01+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         1.00000000e+00+0.j],
       [ 8.00000000e-01+0.j,  6.00000000e-01+0.j,  2.00000000e-01+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         5.00000000e-01+0.j],
       [ 4.00000000e-01+0.j,  7.00000000e-01+0.j,  9.00000000e-01+0.j,
        ...,  5.00000000e-01+0.j,  5.00000000e-01+0.j,
         5.00000000e-01+0.j]])

In [761]:
tryy

array([[0.6 , 0.4 , 0.9 ],
       [0.3 , 0.1 , 0.7 ],
       [0.1 , 0.5 , 0.8 ],
       [0.55, 0.45, 0.5 ],
       [0.7 , 0.7 , 0.7 ]])

In [767]:
u1

array([[ 0.07812161+0.j, -0.05379933+0.j, -0.00267155+0.j, ...,
        -0.03391413+0.j, -0.06920788+0.j, -0.00327728+0.j],
       [ 0.0701247 +0.j, -0.08664024+0.j,  0.04779709+0.j, ...,
         0.01223318+0.j, -0.0877018 +0.j, -0.01684056+0.j],
       [ 0.07823686+0.j, -0.02628904+0.j, -0.07499714+0.j, ...,
        -0.09471574+0.j,  0.02106362+0.j, -0.02481353+0.j],
       ...,
       [ 0.0802177 +0.j, -0.06758194+0.j,  0.10341416+0.j, ...,
         0.00256176+0.j, -0.07122406+0.j,  0.04218962+0.j],
       [ 0.07359448+0.j, -0.03444004+0.j, -0.01977233+0.j, ...,
         0.02407151+0.j,  0.0171289 +0.j, -0.03242935+0.j],
       [ 0.07414222+0.j, -0.0345291 +0.j, -0.04805615+0.j, ...,
        -0.06332383+0.j, -0.06577467+0.j, -0.0253515 +0.j]])

In [763]:
u2, s3, vt2 = np.linalg.svd(A, full_matrices=None)

In [764]:
s3

array([36.20153972,  7.67804824,  6.29459062,  5.24753402,  4.5657905 ,
        4.50341752,  4.34175497,  4.18336738,  3.94746218,  3.49111945,
        3.38346915,  3.26918508,  2.98385955,  2.7992114 ,  2.69771477,
        2.65503831,  2.47185126,  2.32602405,  2.09837352,  2.02228153,
        1.68776752,  1.4943241 ,  1.23985447,  1.08729528,  0.95417649])

In [765]:
u2

array([[-0.07812161,  0.05379933, -0.00267155, ...,  0.03391413,
        -0.06920788, -0.00327728],
       [-0.0701247 ,  0.08664024,  0.04779709, ..., -0.01223318,
        -0.0877018 , -0.01684056],
       [-0.07823686,  0.02628904, -0.07499714, ...,  0.09471574,
         0.02106362, -0.02481353],
       ...,
       [-0.0802177 ,  0.06758194,  0.10341416, ..., -0.00256176,
        -0.07122406,  0.04218962],
       [-0.07359448,  0.03444004, -0.01977233, ..., -0.02407151,
         0.0171289 , -0.03242935],
       [-0.07414222,  0.0345291 , -0.04805615, ...,  0.06332383,
        -0.06577467, -0.0253515 ]])

In [766]:
vt2

array([[-0.28281028, -0.24410369, -0.21658423, -0.21434445, -0.29457654,
        -0.27010085, -0.24784103, -0.21576872, -0.19394953, -0.20059581,
        -0.21314847, -0.17178088, -0.2017699 , -0.19014814, -0.19539099,
        -0.13955983, -0.13991119, -0.13444302, -0.13762167, -0.13038796,
        -0.14976644, -0.16957587, -0.16760666, -0.16474796, -0.18038753],
       [-0.1422603 ,  0.03423064, -0.08012766,  0.17334501, -0.10539003,
        -0.27764625, -0.25241733, -0.14111759, -0.13114818, -0.12052436,
        -0.21826432,  0.09175608, -0.03592491, -0.07386997, -0.09550348,
         0.33306331,  0.35317946,  0.34062961,  0.34310349,  0.30796995,
         0.21130947,  0.15523212,  0.10827369,  0.147636  ,  0.01077955],
       [-0.06948377, -0.12279129, -0.23548971,  0.37417348,  0.01817165,
        -0.11980998, -0.27060138, -0.07757029, -0.17929653, -0.12044131,
         0.22330193,  0.03318049,  0.10261058,  0.04899593,  0.12097743,
        -0.23881443, -0.19002758, -0.16095793, -0