In [50]:
import pandas as pd
import numpy as np
import math
from decimal import Decimal

In [51]:
df = pd.read_excel('Course Recommendation System(1-157).xlsx')

In [52]:
df

ID          Start time     Completion time      Email  Name  \
0      6 2023-01-30 14:04:19 2023-01-30 14:05:54  anonymous   NaN   
1      7 2023-01-30 14:04:44 2023-01-30 14:12:35  anonymous   NaN   
2      8 2023-01-30 14:11:07 2023-01-30 14:12:47  anonymous   NaN   
3      9 2023-01-30 19:10:54 2023-01-30 19:12:35  anonymous   NaN   
4     10 2023-01-30 22:58:02 2023-01-30 23:00:34  anonymous   NaN   
..   ...                 ...                 ...        ...   ...   
152  158 2023-02-24 11:57:27 2023-02-24 11:59:52  anonymous   NaN   
153  159 2023-02-24 11:58:40 2023-02-24 12:00:19  anonymous   NaN   
154  160 2023-02-24 13:28:19 2023-02-24 13:29:35  anonymous   NaN   
155  161 2023-02-24 13:54:02 2023-02-24 13:56:23  anonymous   NaN   
156  162 2023-02-24 14:20:33 2023-02-24 14:22:00  anonymous   NaN   

    Name(not mandatory)\n  Data Structures and Algorithms  \
0                     NaN                            0.30   
1              Rahul Jain                            0.70   
2                     NaN                            0.70   
3            Adrij Sharma                            0.65   
4                     NaN                            0.70   
..                    ...                             ...   
152                   NaN                            0.50   
153                   NaN                            0.70   
154                   NaN                            1.00   
155                   NaN                            1.00   
156                   NaN                            0.70   

     Computer Architecture\n  Discrete Mathematics\n  Economics  ...  \
0                       0.85                    0.85       0.90  ...   
1                       0.80                    0.20       0.80  ...   
2                       0.00                    1.00       1.00  ...   
3                       0.70                    0.20       0.75  ...   
4                       0.60                    0.20       0.00  ...   
..                       ...                     ...        ...  ...   
152                     1.00                    0.10       0.30  ...   
153                     0.80                    0.50       0.60  ...   
154                     0.00                    0.00       1.00  ...   
155                     1.00                    0.70       0.50  ...   
156                     0.10                    0.80       0.90  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          NaN                       NaN           NaN   
1                          NaN                       NaN           NaN   
2                          NaN                       NaN           NaN   
3                          NaN                       NaN           NaN   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
152                        1.0                       1.0           1.0   
153                        NaN                       NaN           NaN   
154                        NaN                       NaN           NaN   
155                        0.0                       0.0           0.0   
156                        0.1                       0.1           0.1   

     VLSI Architecture Design\n  \
0                           NaN   
1                           NaN   
2                           NaN   
3                           NaN   
4                           0.0   
..                          ...   
152                         1.0   
153                         NaN   
154                         NaN   
155                         0.5   
156                         0.1   

     High level synthesis and optimization of Digital Circuits   \
0                                                  NaN            
1                                                  NaN            
2                                                  NaN            
3

In [53]:
df.drop(labels = ['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Name(not mandatory)\n'], axis = 1, inplace = True)

In [54]:
df.fillna(0.5, inplace=True)

In [55]:
df

Data Structures and Algorithms  Computer Architecture\n  \
0                              0.30                     0.85   
1                              0.70                     0.80   
2                              0.70                     0.00   
3                              0.65                     0.70   
4                              0.70                     0.60   
..                              ...                      ...   
152                            0.50                     1.00   
153                            0.70                     0.80   
154                            1.00                     0.00   
155                            1.00                     1.00   
156                            0.70                     0.10   

     Discrete Mathematics\n  Economics  Programming-2  Machine Learning\n  \
0                      0.85       0.90           0.70                0.70   
1                      0.20       0.80           0.80                0.50   
2                      1.00       1.00           1.00                1.00   
3                      0.20       0.75           0.75                0.75   
4                      0.20       0.00           0.80                0.50   
..                      ...        ...            ...                 ...   
152                    0.10       0.30           1.00                1.00   
153                    0.50       0.60           0.80                0.50   
154                    0.00       1.00           1.00                1.00   
155                    0.70       0.50           0.30                0.80   
156                    0.80       0.90           0.70                0.60   

     Mathematics For Machine Learning\n  Visual Recognition\n  \
0                                  0.80                  0.50   
1                                  0.10                  0.20   
2                                  1.00                  0.80   
3                                  0.75                  0.75   
4                                  0.60                  0.40   
..                                  ...                   ...   
152                                0.60                  1.00   
153                                0.50                  0.50   
154                                1.00                  1.00   
155                                0.40                  0.70   
156                                0.60                  0.30   

     Natural Language Processing\n  Reinforcement Learning  ...  \
0                              0.5                     0.5  ...   
1                              0.5                     0.5  ...   
2                              0.9                     1.0  ...   
3                              0.5                     0.5  ...   
4                              0.4                     0.2  ...   
..                             ...                     ...  ...   
152                            0.3                     0.0  ...   
153                            0.5                     0.5  ...   
154                            1.0                     0.0  ...   
155                            0.8                     1.0  ...   
156                            0.1                     0.1  ...   

     Digital CMOS VLSI Design   System design with FPGA   ASIC design   \
0                          0.5                       0.5           0.5   
1                          0.5                       0.5           0.5   
2                          0.5                       0.5           0.5   
3                          0.5                       0.5           0.5   
4                          0.0                       0.0           0.0   
..                         ...                       ...           ...   
152                        1.0                       1.0           1.0   
153                        0.5                       0.5           0.5   
154                        0.5                       0.5   

In [56]:
A = np.asarray(df)

In [57]:
A

array([[0.3 , 0.85, 0.85, ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.8 , 0.2 , ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.  , 1.  , ..., 0.5 , 0.5 , 0.5 ],
       ...,
       [1.  , 0.  , 0.  , ..., 0.5 , 0.5 , 0.5 ],
       [1.  , 1.  , 0.7 , ..., 0.  , 0.  , 0.  ],
       [0.7 , 0.1 , 0.8 , ..., 0.6 , 0.1 , 0.1 ]])

# Truncated SVD -
We will do the folloing steps:-
* QR-Deccomposition
* Eigen Decomposition
* Truncated Singular Value Decomposition

In [58]:
def vector_norm(x):
    """Compute the L2 norm of a vector."""
    return Decimal(np.dot(x, x)).sqrt()

def qr_decomposition(A):
    """
    Compute the QR decomposition of a matrix A using the Gram-Schmidt algorithm.

    Parameters:
    A (numpy.ndarray): The matrix to decompose.

    Returns:
    (numpy.ndarray, numpy.ndarray): A tuple of Q and R matrices that represent the QR decomposition of A, where:
        Q (numpy.ndarray): The orthogonal matrix Q.
        R (numpy.ndarray): The upper triangular matrix R.
    """
    # Get the shape of the input matrix
    m, n = A.shape

    # Initialize the matrices
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    # Perform the Gram-Schmidt orthogonalization
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        # R[j, j] = np.linalg.norm(v)
        R[j, j] = vector_norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

In [59]:
def eig(A):
    """
    Compute the eigenvalues and eigenvectors of a matrix A using the power iteration method.

    Parameters:
    A (numpy.ndarray): The matrix to compute eigenvalues and eigenvectors.

    Returns:
    (eigvals, eigvecs): A tuple of arrays that represent the eigenvalues and eigenvectors of A, where:
        eigvals (numpy.ndarray): The eigenvalues of A.
        eigvecs (numpy.ndarray): The eigenvectors of A.
    """
    # set the number of iterations and tolerance level
    max_iter = 100
    tol = 1e-6

    # initialize the eigenvectors
    m, n = A.shape
    eigvecs = np.random.randn(n, n)

    # compute the largest eigenvalue and eigenvector
    for i in range(max_iter):
        # compute the new eigenvector
        eigvecs_new = A @ eigvecs
        # eigvecs_new, _ = np.linalg.qr(eigvecs_new)
        eigvecs_new, _ = qr_decomposition(eigvecs_new)
        if np.allclose(eigvecs_new, eigvecs, rtol=tol):
            break
        eigvecs = eigvecs_new

    # compute the eigenvalues
    eigvals = np.diag(eigvecs.T @ A @ eigvecs)

    return eigvals, eigvecs


In [60]:
def SVD(A):
    """
    Compute Singular Value Decomposition of matrix A using NumPy.

    Args:
        A: numpy.array, matrix to be decomposed

    Returns:
        U: numpy.array, matrix containing left singular vectors
        s: numpy.array, array containing singular values
        V_T: numpy.array, matrix containing right singular vectors (transposed)
    """
    # Compute the eigenvectors and eigenvalues of A*At or At*A, whichever is smaller
    if A.shape[0] < A.shape[1]:
        S = np.dot(A, A.T)
    else:
        S = np.dot(A.T, A)
        
    # eigvals, eigvecs = np.linalg.eig(S) #NOT ALLOWED
    eigvals, eigvecs = eig(S)

    # Sort the eigenvectors by descending eigenvalues
    sorted_indices = np.argsort(eigvals)[::-1]
    eigvals = eigvals[sorted_indices]
    eigvecs = eigvecs[:,sorted_indices]

    # Compute the singular values and their reciprocals
    s = np.sqrt(eigvals)
    s_inv = np.zeros_like(A.T)
    np.fill_diagonal(s_inv, 1.0 / s)

    # Compute the left and right singular vectors
    U = np.dot(A, np.dot(eigvecs, s_inv))
    V_T = eigvecs.T

    if(len(s) != U.shape[0]): U = U[:, :len(s) - U.shape[0]]
    sigma = np.zeros([U.shape[1], V_T.shape[0]])
    
    for i in range(len(s)):
        sigma[i, i] = s[i]

    return U, s, sigma, V_T

# SVD on Data

In [61]:
tryy = np.array([[0.6, 0.4, 0.9], [0.3, 0.1, 0.7], [0.1, 0.5, 0.8], [0.55, 0.45, 0.5], [0.7, 0.7 , 0.7]])

In [62]:
U, s, sigma, V_trans = SVD(A)

In [63]:
sigma.shape

(25, 25)

In [64]:
np.allclose(U @ sigma @ V_trans, A)

True

# Reduced SVD

In [65]:
def ReducedSVD(A, threshold = 0, to_remove = 0):
    U, s, sigma, V_trans = SVD(A)

    # While converting to python code we will convert into GUI asking-
    #       - Removal based on:-
    #       - 1. Hyper parameter
    #       - 2. Threshold
    
    # Removal based on hyper parameter
    if(to_remove < len(s) and to_remove > 0):
        s = s[:-to_remove]
        print(s)
        U = U[:, :-to_remove]
        V_trans = V_trans[:-to_remove, :]
        sigma = sigma[:-to_remove, :-to_remove]

    elif(to_remove < 0):
        print("The number of eigen values to be romved is Invalid!!")
        exit()
        
    # Removal based on threshold
    if(threshold < s[0] and threshold > 0):
        s = s[s >= threshold]
        print(s)
        U = U[:, :len(s)]
        V_trans = V_trans[:len(s), :]
        sigma = sigma[:len(s), :len(s)]

    elif(threshold < 0):
        print("Invalid threshold value!!")
        exit()
        
    return U, s, sigma, V_trans
    

# Reduced SVD on Data

In [66]:
u1, s2, sig1, vt1 = ReducedSVD(A,0,2)

[35.74969686  7.59197365  6.23819765  5.2164577   4.55387788  4.48862244
  4.31460042  4.16166021  3.85568719  3.42461967  3.36781129  3.22257511
  2.87590798  2.78615119  2.62207032  2.59558772  2.42302529  2.29458924
  2.09329895  2.00407326  1.67617231  1.49079117  1.23503577]


In [67]:
u1 @ sig1 @ vt1

array([[ 3.03911055e-01,  8.47043008e-01,  8.44925813e-01, ...,
         5.02110866e-01,  5.11492463e-01,  5.06359109e-01],
       [ 7.03650811e-01,  7.96471415e-01,  1.94265069e-01, ...,
         5.01822877e-01,  5.13767067e-01,  5.07782649e-01],
       [ 6.97527038e-01,  2.87477887e-04,  1.00115249e+00, ...,
         4.98361497e-01,  4.98992030e-01,  4.99781907e-01],
       ...,
       [ 1.00275318e+00,  2.39173475e-04, -5.56431808e-04, ...,
         5.01931540e-01,  4.98910093e-01,  4.98898747e-01],
       [ 1.02792457e+00,  9.97506049e-01,  6.87963584e-01, ...,
         1.86463295e-02,  8.40638552e-03,  6.54757582e-04],
       [ 6.98640249e-01,  9.94487268e-02,  7.99711987e-01, ...,
         5.98962875e-01,  1.02251667e-01,  1.01584934e-01]])

In [68]:
A

array([[0.3 , 0.85, 0.85, ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.8 , 0.2 , ..., 0.5 , 0.5 , 0.5 ],
       [0.7 , 0.  , 1.  , ..., 0.5 , 0.5 , 0.5 ],
       ...,
       [1.  , 0.  , 0.  , ..., 0.5 , 0.5 , 0.5 ],
       [1.  , 1.  , 0.7 , ..., 0.  , 0.  , 0.  ],
       [0.7 , 0.1 , 0.8 , ..., 0.6 , 0.1 , 0.1 ]])